# b. Grunnleggende numpy-array

In [16]:
import numpy as np

# Leser inn data fra en CSV-fil
# 'delimiter' angir at hver verdi er separert med et semikolon
# 'dtype=int' angir at vi ønsker å konvertere disse verdiene til heltall, kan også være "float" eller "str"

målinger = np.genfromtxt(r'..\data\04_numpy_array.csv', delimiter=';', dtype=int, skip_header=1)
print(målinger)

[[ 45  30]
 [ 60  20]
 [ 30  40]
 [ 85  15]
 [ 90  35]
 [120  25]
 [150  30]
 [210  20]
 [270  10]]


# c. Operasjoner med geologiske numpy arrays:

In [17]:
# Beregn gjennomsnittlig strøk og fall
gjennomsnitt_strøk = np.mean(målinger[:, 0])
print("Gj.strøk: ", gjennomsnitt_strøk)
gjennomsnitt_fall = np.mean(målinger[:, 1])
print("Gj.fall: ", gjennomsnitt_fall)

Gj.strøk:  117.77777777777777
Gj.fall:  25.0


# d. Nyttige numpy funksjoner for geologiske data:

In [20]:
# Finn maksimum og minimum fall-verdier
max_fall = np.max(målinger[:, 1])
print("Maks fall: ", max_fall)
min_fall = np.min(målinger[:, 1])
print("Min fall: ", min_fall)

# Beregn standardavvik for strøk-verdier
std_dev_strøk = np.std(målinger[:, 0])
print("Std.avvik strøk: ", std_dev_strøk)

Maks fall:  40
Min fall:  10
Std.avvik strøk:  75.20753180038668


# e. Indeksering og skjæring av geologiske data:

In [25]:
# Hent første strøk/fall-måling
første_måling = målinger[0]
print(første_måling)

# Hent alle strøk-verdier
alle_strøk = målinger[:, 0]
print(alle_strøk)

# Hent strøk/fall-målinger med fall større enn 25 grader
høyt_fall = målinger[målinger[:, 1] > 25]
print(høyt_fall)

[45 30]
[ 45  60  30  85  90 120 150 210 270]
[[ 45  30]
 [ 30  40]
 [ 90  35]
 [150  30]]
